name: Get latest V8 stable version

on:
  schedule:
  - cron: '0 */12 * * *'
  push:
    branches: [ main ]
    paths:
    - 'get_version.py'
    - '.github/workflows/get_version.yml'
  workflow_dispatch:

permissions: write-all

jobs:
  version_finder:
    name: Get version number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Fetch tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: "Get version"
      id: ver
      run: |
        cd $GITHUB_WORKSPACE
        pip install pandas
        version=$(python ./get_version.py)
        
        if [ $? -eq 0 ]; then
          echo "ver=$version" >> $GITHUB_OUTPUT
        else
          echo "Failed to retrieve V8 version"
          exit 1
        fi
    - name: 'Check: package version has corrosponding git tag'
      id: tagged
      shell: bash
      run: git show-ref --tags --verify --quiet -- "refs/tags/${{ steps.ver.outputs.ver }}" && echo "tagged=0" >> $GITHUB_OUTPUT || echo "tagged=1" >> $GITHUB_OUTPUT
    - name: Step to only run if there is no git-tag for the version
      if: steps.tagged.outputs.tagged == 1
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.ver.outputs.ver }}
        release_name: V8 Build (${{ steps.ver.outputs.ver }})
